name: HeadsPluginAPI
version: ${version}
api-version: "1.13"
main: com.github.cc007.headsplugin.HeadsPlugin
author: Rik Schaaf aka CC007 (http://coolcat007.nl/)
loadbefore: [zPermissions]
description: >
  The base heads API for other plugins to use
commands:
  headspluginapi:
    description: "Commands for the HeadsPluginAPI"
    aliases: [headsplugin, hdspluginapi, hdsplugin, hpa, hp]
permissions:
  headspluginapi.update:
    description: Allows the user register the heads plugin