# used for new version detection
version: ${project.version}

headsplugin:
  # define which heads database should be enabled.
  provider:
    freshcoal: true
    mineskin: true
    minecraftHeads: true
  suppressHttpClientErrors: true
  search:
    update:
      # search update interval in minutes
      interval: 1440 # 1 day
  categories:
    update:
      # category update interval in hours
      interval: 168 # 1 week
      notify: [] # list of player names to notify when the update is done
      notifyEach: [] # list of player names to notify when each category is updated
    # define your custom categories here
    custom:
      - name: pokemon-starters
        # the contents of a category is based on search terms
        searchTerms:
          - pikachu
          - bulbasaur
          - squirtle
          # you can also use a UUID to add a head to the category
          - uuid:cd9fd81b-cc17-4d5c-8765-04e5069b026c #charmander
      - name: cats-and-dogs
        searchTerms:
          - cat
          - dog

profiler:
  defaultLogLevel: DEBUG

database:
  chunkSize: 500
