# used for new version detection
version: ${project.version}

# config for the freshcoal api
freshcoal:
  # server to look for the category heads
  predefinedcategoriesurl: https://freshcoal.com/mainapi.php?query=

  # server to look for the custom heads
  customcategoriesurl: https://freshcoal.com/api.php?query=

# config for the mineskin api
mineskin:
  # server to look for the custom heads using the mineskin api
  customcategoriesurl: http://api.mineskin.org/get/

  # server to save new custom heads to using the mineskin api
  generateurl: http://api.mineskin.org/generate/user/

# config for the minecraft-heads api
minecraftheads:
  # server to look for the category heads using the minecraft-heads website
  predefinedcategoriesurl: https://minecraft-heads.com/scripts/api.php?tags=true&cat=

  ## server to look for the custom heads using the minecraft-heads website (not available yet
  # customcategoriesurl:

# maximum response time from the server to respond
connectiontimeout: 10000

headsplugin:
  categories:
    update:
      # category update interval in hours
      interval: 24
  search:
    update:
      # search update interval in minutes
      interval: 5

hibernate:
  enable_lazy_load_no_trans: true

spring:
  datasource:
    url: jdbc:hsqldb:file:plugins/HeadsPluginAPI/data/heads
    username: sa
    password: ""
    driverClassName: org.hsqldb.jdbcDriver

  hsql:
    console:
      enabled: true

  jpa:
    database: HSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.HSQLDialect
    show-sql: true
    properties:
      hibernate.jdbc.batch_size: 1000
      hibernate.order_inserts: true
      hibernate.jdbc.batch_versioned_data: true
      hibernate.enable_lazy_load_no_trans: true