# used for new version detection
version: ${project.version}

# maximum response time from the server to respond
connectiontimeout: 10000

headsplugin:
  categories:
    update:
      # category update interval in hours
      interval: 24
  search:
    update:
      # search update interval in minutes
      interval: 5

hibernate:
  enable_lazy_load_no_trans: true

spring:
  datasource:
    url: jdbc:hsqldb:file:plugins/HeadsPluginAPI/data/heads
    username: sa
    password: ""
    driverClassName: org.hsqldb.jdbcDriver

  hsql:
    console:
      enabled: true

  jpa:
    database: HSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.HSQLDialect
    show-sql: true
    properties:
      hibernate.jdbc.batch_size: 1000
      hibernate.order_inserts: true
      hibernate.jdbc.batch_versioned_data: true
      hibernate.enable_lazy_load_no_trans: true