# used for new version detection
version: ${project.version}

headsplugin:
  categories:
    custom:
      - name: pokemon-starters
        searchTerms:
          - pikachu
          - bulbasaur
          - squirtle
          - uuid:cd9fd81b-cc17-4d5c-8765-04e5069b026c #charmander
      - name: cats-and-dogs
        searchTerms:
          - cat
          - dog

    update:
      # category update interval in hours
      interval: 168 # 1 week
  search:
    update:
      # search update interval in minutes
      interval: 1440 # 1 day

spring:
  datasource:
    url: jdbc:hsqldb:file:plugins/HeadsPluginAPI/data/heads
    username: sa
    password: ""
    driverClassName: org.hsqldb.jdbcDriver

  hsql:
    console:
      enabled: true

  jpa:
    database: HSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.HSQLDialect
    show-sql: true
    properties:
      hibernate.jdbc.batch_size: 1000
      hibernate.order_inserts: true
      hibernate.jdbc.batch_versioned_data: true
      hibernate.enable_lazy_load_no_trans: true