package com.github.cc007.headsplugin.integration.daos.services;

import com.github.cc007.headsplugin.integration.daos.interfaces.Categorizable;

import java.util.Map;
import java.util.Set;

public interface CategorizableUtils {

    /**
     * Get a map with category names as keys and a set of {@link Categorizable}s as values for those keys.
     * One category could be available for multiple catagorizables. That's why they are supplied in a set.
     *
     * This value will be cached after the first call to {@link #getCategoryMap()}.
     * If you need the value to change, you can call {@link #clearCategoryMap()} to clear the cache.
     *
     * @return the map of catagorizables for each category
     */
    Map<String, Set<Categorizable>> getCategoryMap();

    /**
     * Clears the cached value that is generated by {@link #getCategoryMap()}.
     * This may be needed if the config has reloaded with new categories.
     */
    void clearCategoryMap();
}
